name: Medium workflow
on: push
jobs:
  job1:
    name: job1 name
    runs-on: ubuntu-latest # Ubuntu runner
    steps:
    - name: step11
      uses: actions/checkout@v2
    - name: step21
      run: env # runs a Bash command on Ubuntu
  job2:
    name: job2 name
    runs-on: ubuntu-latest # Ubuntu runner
    needs: [job1]
    steps:
    - name: step21
      uses: actions/checkout@v2
    - name: step21
      run: ls -all # runs a Bash command on Ubuntu
    - name: step22
      run: docker images #
    
  
  
