name: example

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step11
        uses: actions/checkout@v2
      - name: step12
        run: ls
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - name: step21
        uses: actions/checkout@v2
      - name: step22
        run: ls -all
    
  
  
